/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EdgeAlert {
        "headertitle": string;
    }
    interface EdgeButton {
        "class": "btn-default" | "btn-primary" | "btn-info" | "btn-success" | "btn-warning" | "btn-danger";
        "title": string;
    }
    interface EdgeCard {
        "avatar": string;
        "description": string;
        "firstname": string;
        "lastname": string;
    }
    interface EdgeProgressBar {
        "class": string;
        "color": string;
        "dlabel": string;
        "max": number;
        "value": number;
    }
}
declare global {
    interface HTMLEdgeAlertElement extends Components.EdgeAlert, HTMLStencilElement {
    }
    var HTMLEdgeAlertElement: {
        prototype: HTMLEdgeAlertElement;
        new (): HTMLEdgeAlertElement;
    };
    interface HTMLEdgeButtonElement extends Components.EdgeButton, HTMLStencilElement {
    }
    var HTMLEdgeButtonElement: {
        prototype: HTMLEdgeButtonElement;
        new (): HTMLEdgeButtonElement;
    };
    interface HTMLEdgeCardElement extends Components.EdgeCard, HTMLStencilElement {
    }
    var HTMLEdgeCardElement: {
        prototype: HTMLEdgeCardElement;
        new (): HTMLEdgeCardElement;
    };
    interface HTMLEdgeProgressBarElement extends Components.EdgeProgressBar, HTMLStencilElement {
    }
    var HTMLEdgeProgressBarElement: {
        prototype: HTMLEdgeProgressBarElement;
        new (): HTMLEdgeProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "edge-alert": HTMLEdgeAlertElement;
        "edge-button": HTMLEdgeButtonElement;
        "edge-card": HTMLEdgeCardElement;
        "edge-progress-bar": HTMLEdgeProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface EdgeAlert {
        "headertitle"?: string;
    }
    interface EdgeButton {
        "class"?: "btn-default" | "btn-primary" | "btn-info" | "btn-success" | "btn-warning" | "btn-danger";
        "onName"?: (event: CustomEvent<string>) => void;
        "title"?: string;
    }
    interface EdgeCard {
        "avatar"?: string;
        "description"?: string;
        "firstname"?: string;
        "lastname"?: string;
    }
    interface EdgeProgressBar {
        "class"?: string;
        "color"?: string;
        "dlabel"?: string;
        "max"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "edge-alert": EdgeAlert;
        "edge-button": EdgeButton;
        "edge-card": EdgeCard;
        "edge-progress-bar": EdgeProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "edge-alert": LocalJSX.EdgeAlert & JSXBase.HTMLAttributes<HTMLEdgeAlertElement>;
            "edge-button": LocalJSX.EdgeButton & JSXBase.HTMLAttributes<HTMLEdgeButtonElement>;
            "edge-card": LocalJSX.EdgeCard & JSXBase.HTMLAttributes<HTMLEdgeCardElement>;
            "edge-progress-bar": LocalJSX.EdgeProgressBar & JSXBase.HTMLAttributes<HTMLEdgeProgressBarElement>;
        }
    }
}
